name: On Pull Request

on:
  pull_request:
    branches:
    - main

jobs:
  kustomize:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # - name: Install Kustomize
      # run: curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
    - run: cd hello-world && kustomize build overlays/staging